import fs from 'fs';
import path from 'path';
import zlib from 'zlib';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PLUGIN_DIR = path.resolve(__dirname, '..');
const ASSETS_DIR = path.join(PLUGIN_DIR, 'assets');
const OUT_FILE = path.join(PLUGIN_DIR, 'src', 'toolchain', 'embeddedAssets.ts');
const MANIFEST_FILE = path.join(PLUGIN_DIR, 'manifest.json');

const TEXT_EXTENSIONS = new Set([
  '.md',
  '.mjs',
  '.ts',
  '.tsx',
  '.json',
  '.yml',
  '.yaml',
  '.html',
  '.css',
  '.gitignore',
]);

function isTextFile(relativePath) {
  if (relativePath.endsWith('.template')) {
    return true;
  }
  return TEXT_EXTENSIONS.has(path.extname(relativePath));
}

function shouldEmbed(relativePath) {
  return !relativePath.startsWith('template/') && !relativePath.includes('/template/');
}

function walkFiles(dir, relative = '') {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = relative ? `${relative}/${entry.name}` : entry.name;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkFiles(full, rel));
    } else if (entry.name !== 'manifest.json') {
      files.push(rel);
    }
  }
  return files;
}

function readAssetEntry(toolchainName, relativePath) {
  const absolute = path.join(ASSETS_DIR, toolchainName, relativePath);
  if (isTextFile(relativePath)) {
    return {
      path: `${toolchainName}/${relativePath}`,
      encoding: 'utf8',
      data: fs.readFileSync(absolute, 'utf8'),
    };
  }
  return {
    path: `${toolchainName}/${relativePath}`,
    encoding: 'base64',
    data: fs.readFileSync(absolute).toString('base64'),
  };
}

function buildToolchainBundle(toolchainName) {
  const toolchainDir = path.join(ASSETS_DIR, toolchainName);
  const relativeFiles = walkFiles(toolchainDir).filter(shouldEmbed).sort();
  const entries = relativeFiles.map((rel) => readAssetEntry(toolchainName, rel));

  const manifestPaths = relativeFiles.map((rel) => rel.replace(/\\/g, '/'));
  entries.push({
    path: `${toolchainName}/manifest.json`,
    encoding: 'utf8',
    data: `${JSON.stringify(manifestPaths, null, 2)}\n`,
  });

  return entries;
}

const pluginVersion = JSON.parse(fs.readFileSync(MANIFEST_FILE, 'utf8')).version;
const bundle = {
  files: [
    ...buildToolchainBundle('toolchain-quartz'),
    ...buildToolchainBundle('toolchain-inhouse'),
  ],
};

const compressed = zlib.gzipSync(JSON.stringify(bundle));
const encoded = compressed.toString('base64');

const source = `/** Generated by scripts/embed-assets.mjs — do not edit. */
export const EMBEDDED_ASSETS_VERSION = ${JSON.stringify(pluginVersion)};
export const EMBEDDED_ASSETS_BUNDLE = ${JSON.stringify(encoded)};
`;

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, source);

console.log(
  `Embedded ${bundle.files.length} asset files (gzip ${compressed.length} bytes) at v${pluginVersion}`,
);
